version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: csv-to-json-rabbitmq

    ports:
      - 5672:5672
      - 15672:15672

    volumes:
      - rabbitmqdata_csv_to_json:/var/lib/rabbitmq

    env_file:
      - .env

    restart: always

volumes:
  rabbitmqdata_csv_to_json:
